# Generated by Django 2.0.5 on 2019-05-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentState', models.BooleanField(default=False)),
                ('currentTotal', models.IntegerField(default=0)),
                ('currentVar', models.IntegerField(default=0)),
                ('result', models.TextField(default='[]')),
            ],
        ),
    ]
