# Generated by Django 2.0.5 on 2019-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsing',
            name='info',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
